from Myro import * #should always be first line
init("sim") #should also always be there
size=float(input("How big should the square be? Should be less than 5.5 if you don't want to run out of space"))
penDown()
def SquareySquare():
    forward(size,1)
    wait(.5)
    penUp()
    turnTo(90)
    penDown()
    forward(size,1)
    wait(.5)
    penUp()
    turnTo(180)
    penDown()
    forward(size,1)
    wait(.5)
    penUp()
    turnTo(0)
    penDown()
    forward(size,1)
def RandomShape():
    move(1,1)
    wait(10)
    stop()
SquareySquare()
penUp()
forward(.5,1)
penDown()
RandomShape()
