from Myro import * #should always be first line
init("sim") #should also always be there
size=float(input("How big should the square be? Should be less than 5.5 if you don't want to run out of space"))
penDown()
forward(size,1)
wait(.5)
penUp()
turnLeft(.60,1)
turnLeft(.61,1)
turnLeft(.62,1)
turnLeft(.62,1)
penDown()
forward(size,1)
wait(.5)
penUp()
turnLeft(.60,1)
turnLeft(.61,1)
turnLeft(.62,1)
turnLeft(.62,1)
penDown()
forward(size,1)
wait(.5)
penUp()
turnLeft(.60,1)
turnLeft(.61,1)
turnLeft(.62,1)
turnLeft(.62,1)
penDown()
forward(size,1)
